question_data = [
    {"category": "Mythology",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In Norse mythology, Thor once dressed as a woman.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "easy",
     "question": "According to Greek Mythology, Zeus can control lightning.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "medium",
     "question": "According to Norse mythology, Loki is a mother.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "medium",
     "question": "The Japanese god Izanagi successfully returned his wife Izanami from the Underworld.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "hard",
     "question": "Rannamaari was a sea demon that haunted the people of the Maldives and had to be appeased monthly with the sacrifice of a virgin girl.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "medium",
     "question": "In Greek mythology, Hera is the goddess of harvest.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "easy",
     "question": "According to Greek Mythology, Atlas was an Olympian God.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "easy",
     "question": "A wyvern is the same as a dragon.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Mythology", "type": "boolean", "difficulty": "hard",
     "question": "Janus was the Roman god of doorways and passageways.",
     "correct_answer": "True", "incorrect_answers": ["False"]}
]
